@echo off
cls
echo/
>nul 2>&1 dism|| (echo Admin rights required!& goto quit)
ver| >nul find "10.0."|| (echo Windows 10 only.& goto quit)
set x=& if defined ProgramFiles(x86) set "x= (x86)"
if exist "%ProgramFiles%%x%\StartIsBack\StartIsBackCfg.exe" echo StartIsBack already installed.& goto quit

choice /c 10 /n /m "Download (if necessary) and install """StartIsBack++ 2.9.15"""? [1=Yes/0=No]"
if %errorlevel% gtr 1 exit

echo/
cd /d "%~dp0"
if exist StartIsBackPlusPlus_setup.exe echo StartIsBack already exists.& goto chk
>tst.vbs echo Set x = CreateObject("Microsoft.XMLHTTP") : x.Open "GET", WScript.Arguments(0), False : x.Send : With CreateObject("Adodb.Stream") : .type = 1 : .open : .write x.responseBody : .savetofile WScript.Arguments(1), 2 : End With
<nul set /p "=Download StartIsBack... "
>nul cscript.exe tst.vbs "https://www.startisback.com/StartIsBackPlusPlus_setup.exe" "StartIsBackPlusPlus_setup.exe"
echo done.
del /q tst.vbs

:chk
echo/
<nul set /p "=Checking SHA1... "
certutil.exe -hashfile StartIsBackPlusPlus_setup.exe| >nul find "b93f3d6cbdcc0b44b3ef440d6b6ab22ab18589c1"|| (echo error!& goto quit)
echo done.

StartIsBackPlusPlus_setup.exe /elevated /silent
certutil.exe -decode "%~0" "%ProgramFiles%%x%\StartIsBack\msimg32.dll"
for %%i in ("reg add HKEY_CURRENT_USER\Software\StartIsBack /t REG_DWORD /f /v") do (
%%~i "AutoUpdates" /d 0
%%~i "NoXAMLPrelaunch" /d 1
)
start explorer
exit

:quit
echo/
pause
exit

-----BEGIN CERTIFICATE-----
TVqAAAEAAAAEABAA//8AAEABAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5v
dCBiZSBydW4gaW4gRE9TIG1vZGUuDQokAAAAAAAAAABQRQAATAEBAByMu1wAAAAA
AAAAAOAADiELAQFJAAYAAAAGAAAAAAAAABAAAAAQAAAAEAAAAABAAAAQAAAAAgAA
AQAAAAAAAAADAAoAAAAAAAAgAAAAAgAAezgAAAMAQAAAEAAAABAAAAAAAQAAAAAA
AAAAABAAAADjEQAAqQAAAIwSAAA6AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
xhMAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAA
BgQAAAAQAAAABgAAAAIAAAAAAAAAAAAAAAAAAGAAAOAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVieVgg30MAXVE6BMAAABT
dGFydElzQmFja0NmZy5leGUA/xUAE0AACcB+IoM9sRFAAAB1D2ixEUAAaKURQADo
1gAAAOh4AAAA6JsAAABhuAEAAADJwgwAif9VieVggX0IAQAAgHVPi3UMv8oRQAC5
GAAAAPzzpgnJdTuLPZwTQABqAGgAAgAA/3UM/3UI/9dqAGgAAQAA/3UM/3UI/9dq
AGoFaFgQQAD/NZgTQABq//8VEBNAAGGhmBNAAIPABf/goZgTQAC7WBBAACnDg+sF
iR3GEUAAagBqBWjFEUAAUGr//xUQE0AAw2C/ABBAAIsNAAJAALh0Qo1V/PKuCcl0
FzlH/3X1agBqAWjiEUAAV2r//xUQE0AAYcNVieWB7AgBAABgx0X8BQAAAI2d+P7/
/2gEAQAAU/8VCBNAAOgCAAAAXABT/xUUE0AA/3UIU/8VFBNAAFP/FQwTQACJw79J
EkAAi3UM/FdT/xUEE0AAiQaDxgQwwLn/////8q7/Tfx15WHJwggA/yWxEUAA/yW1
EUAA/yW5EUAA/yW9EUAA/yXBEUAAbXNpbWczMi5kbGwAAAAAAAAAAAAAAAAAAAAA
AAAAAADpAAAAAFNPRlRXQVJFXENsYXNzZXNcQ0xTSURcewAAAAAAAAAAAAAAAAA9
EgAAAQAAAAUAAAAFAAAACxIAAB8SAAAzEgAAhxEAAI0RAACTEQAAmREAAJ8RAABX
EgAAYhIAAHASAAB9EgAASRIAAAEAAgADAAQAAABtc2ltZzMyLmRsbAB2U2V0RGRy
YXdmbGFnAEFscGhhQmxlbmQARGxsSW5pdGlhbGl6ZQBHcmFkaWVudEZpbGwAVHJh
bnNwYXJlbnRCbHQA5BIAAAAAAAAAAAAAyBIAAAATAACMEwAAAAAAAAAAAADWEgAA
mBMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa2VybmVsMzIuZGxsAABhZHZhcGkzMi5k
bGwAABwTAAAwEwAAQhMAAFgTAABoEwAAfhMAAAAAAAAcEwAAMBMAAEITAABYEwAA
aBMAAH4TAAAAAAAAAABHZXRNb2R1bGVIYW5kbGVBAAAAAEdldFByb2NBZGRyZXNz
AAAAAEdldFN5c3RlbURpcmVjdG9yeUEAAABMb2FkTGlicmFyeUEAAAAAV3JpdGVQ
cm9jZXNzTWVtb3J5AAAAAGxzdHJjYXRBAAAAAKQTAAC0EwAAAAAAAKQTAAC0EwAA
AAAAAAAAUmVnQ3JlYXRlS2V5QQAAAFJlZ0RlbGV0ZUtleUV4QQAAEAAAQAAAACQw
LjA2MDswazB9MKQwqjCyMLgwwjDHMNIw2zDkMAsxFDE5MUcxUTFYMV8xazGJMY8x
lTGbMaExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
-----END CERTIFICATE-----
